import {Link} from 'react-router-dom';
import {ArrowUpRight,ScanLine,GitBranch,Radar,Combine,Play,Check,MoveUpRight} from 'lucide-react';
import type {LucideIcon} from 'lucide-react';
import type {ReactNode} from 'react';
import type {SessionDefinition} from '../../content/sessions';
export function SessionFeatured({session,visited,isNext}:{session:SessionDefinition;visited:boolean;isNext:boolean}){
  return <article className="session-featured"><div className="featured-heading"><span className="eyebrow">Laboratorio 01</span><span className="availability"><i/>{visited?'Vuelve a probar':isNext?'Empieza aquí':'Disponible'}</span></div><h3>{session.title}</h3><p>{session.summary}</p><div className="featured-preview"><div className="preview-top"><span>IROH / Pista S01</span><code>{session.dimensions}</code></div><div className="preview-canvas"><img src="/tracks/s01.png" width="160" height="224" alt="Pista S01: salida inferior y bifurcación hacia dos bases"/><div className="preview-annotation"><span>01 — LECTURA</span><strong>Lee la señal.<br/>Elige el camino.</strong><span className="signal-lines" aria-hidden="true"><i/><i/><i/></span></div></div><div className="preview-caption"><span>IR</span><span>Línea</span><span>LCD</span><span>Decisiones</span><a href="/tracks/s01.png" target="_blank" rel="noreferrer" aria-label="Abrir plotter S01 original en otra pestaña"><MoveUpRight size={16}/></a></div></div><Link className="primary featured-cta" to="/intermedio/s01" aria-label={`Abrir S01: ${session.title}`}><Play size={18}/>Entrar al laboratorio<ArrowUpRight size={18}/></Link><small>Simula, calibra y observa tu código en acción.</small></article>;
}
export function SessionRow({session,visited,isNext,icon:Icon}:{session:SessionDefinition;visited:boolean;isNext:boolean;icon:LucideIcon}){
  return <Link to={`/intermedio/${session.id}`} className={`session-row ${visited?'is-visited':''} ${isNext?'is-next':''}`} aria-label={`Abrir ${session.id.toUpperCase()}: ${session.title}. ${session.interactive?'Simulación interactiva':'Material y editor'}`}><span className="path-node" aria-hidden="true"><i/></span><span className="session-number">{session.number.toString().padStart(2,'0')}</span><span className="skill-icon-wrap"><Icon size={19}/></span><div className="session-row-copy"><h3>{session.title}</h3><p>{session.concepts.join(' · ')}</p><span className="row-availability">{session.interactive?'Simulación interactiva':'Material y editor'}{visited&&<><span>·</span><Check size={12}/>Explorada</>}</span></div><ArrowUpRight className="row-arrow" size={18}/></Link>;
}
export const curriculum=[{title:'Fundamentos',range:'01–02',ids:['s02'],icon:ScanLine},{title:'Control y decisiones',range:'03–05',ids:['s03','s04','s05'],icon:GitBranch},{title:'Leer el entorno',range:'06',ids:['s06'],icon:Radar},{title:'Integrar lo aprendido',range:'07–08',ids:['s07','s08'],icon:Combine}];
export function CurriculumSection({title,range,children}:{title:string;range:string;delay:number;children:ReactNode}){return <section className="curriculum-section"><div className="curriculum-heading"><h3>{title}</h3><span>{range}</span></div><div className="curriculum-track">{children}</div></section>;}
