import {useMemo} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,ArrowDown,Terminal,MapPin,BookOpen,Check,CornerDownRight,ScanLine} from 'lucide-react';
import {sessions} from '../../content/sessions';
import {explored,codeKey,lastVisited} from '../code-editor/storage';
import {useAuth} from '../auth/AuthProvider';
import {SessionFeatured,SessionRow,CurriculumSection,curriculum} from './Curriculum';
export function Explorer(){
  const {profile,membership,sites,status}=useAuth();
  const visited=useMemo(()=>new Set(explored()),[]);
  const nextSession=sessions.find(s=>!visited.has(s.id));
  const lastSession=useMemo(()=>sessions.find(s=>s.id===lastVisited())??sessions.map(s=>{try{return {session:s,time:JSON.parse(localStorage.getItem(codeKey(s.id))||'null')?.lastOpenedAt||0};}catch{return {session:s,time:0};}}).sort((a,b)=>b.time-a.time).find(s=>s.time>0)?.session,[]);
  const continueSession=lastSession??nextSession??sessions[0];
  const site=sites.find(s=>s.id===membership?.site_id);
  return <main id="main" className="explorer"><div className="course-context"><span><span className="context-dot"/>Robótica intermedia</span><span className="context-divider"/><span>Recorrido IROH · 8 sesiones</span><span className="context-location">{site?<><MapPin size={14}/>{site.name}</>:<>Práctica libre · sin registro</>}</span></div>
    <section className="session-hero" aria-labelledby="explorer-title"><div className="hero-copy"><span className="eyebrow">{profile?`Tu laboratorio, ${profile.display_name.split(' ')[0]}`:'Aprender es ponerlo a prueba'}</span><h1 id="explorer-title">Del código<br/>al <em>movimiento.</em></h1><p>Programa el IROH. Lee sus sensores, prueba una estrategia y descubre qué puedes hacer mejor.</p><div className="hero-actions"><Link className="primary hero-primary" to={`/intermedio/${continueSession.id}`}><Terminal size={18}/>{lastSession?'Retomar mi práctica':`Comenzar con ${continueSession.id.toUpperCase()}`}<ArrowRight size={18}/></Link><a className="text-link" href="#learning-path">Ver el recorrido<ArrowDown size={16}/></a></div><span className="hero-footnote">Arduino / C++ <span>·</span> El mismo lenguaje de tu taller</span></div>
      <aside className="progress-card" aria-label="Sesiones exploradas"><div className="progress-head"><span className="eyebrow">Bitácora de aprendizaje</span><BookOpen size={18}/></div><div className="progress-total"><strong>{visited.size.toString().padStart(2,'0')}</strong><span>/ 08<br/><small>sesiones exploradas</small></span></div><div className="progress-nodes" aria-label={`${visited.size} de 8 sesiones exploradas`}>{sessions.map(s=><span key={s.id} className={visited.has(s.id)?'done':s.id===nextSession?.id?'next':''} title={`${s.id.toUpperCase()}: ${visited.has(s.id)?'explorada':'por explorar'}`}>{visited.has(s.id)?<Check size={13}/>:s.number.toString().padStart(2,'0')}</span>)}</div><p>{visited.size===0?'Toda buena idea empieza con una primera prueba.':visited.size===8?'Exploraste toda la ruta. Siempre hay algo más que probar.':'Cada prueba cuenta. Continúa a tu ritmo.'}</p><div className="next-mission"><CornerDownRight size={18}/><span>{nextSession?'Próxima por explorar':'Vuelve a practicar'}<strong>{(nextSession??sessions[0]).id.toUpperCase()} · {(nextSession??sessions[0]).title}</strong></span></div></aside></section>
    <div id="learning-path" className="path-heading"><div><span className="eyebrow">01 / Ruta de aprendizaje</span><h2>Una señal. Una decisión.<br className="mobile-break"/> Un nuevo desafío.</h2></div><span className="path-note"><ScanLine size={16}/>S01–S02 con simulación interactiva</span></div>
    <div className="curriculum-layout"><SessionFeatured session={sessions[0]} visited={visited.has('s01')} isNext={nextSession?.id==='s01'}/><div className="curriculum-list">{curriculum.map((group,index)=><CurriculumSection key={group.title} title={group.title} range={group.range} delay={index}>{group.ids.map(id=><SessionRow key={id} session={sessions.find(s=>s.id===id)!} visited={visited.has(id)} isNext={nextSession?.id===id} icon={group.icon}/>)}</CurriculumSection>)}</div></div>
    {status!=='authenticated'&&<section className="account-invitation"><div><span className="eyebrow">Tu práctica tiene un lugar</span><h2>Una cuenta. Tus espacios. Tu recorrido.</h2><p>Organiza tu práctica y habilita programas institucionales mediante códigos de acceso.</p></div><Link className="button" to="/registro">Crear mi cuenta<ArrowRight size={17}/></Link></section>}
    <footer className="page-foot"><span><strong>BITIRO</strong> Aprende, resuelve y crea con tecnología.</span><div><Link to="/privacidad">Datos y privacidad</Link><span>Lab 6.4.1</span></div></footer></main>;
}
