import {Minus,Plus,Maximize2,Minimize2,SlidersHorizontal,X,Map,Box,LocateFixed} from 'lucide-react';
import {IconButton} from '../../components/Controls';
type ViewMode='top'|'perspective'|'follow';
export function SimulatorToolbar({zoom,onZoom,calibration,onCalibration,trackId,viewMode,onViewMode,fullscreen,onFullscreen}:{zoom:number;onZoom:(n:number)=>void;calibration:boolean;onCalibration:()=>void;trackId:string;viewMode:ViewMode;onViewMode:(mode:ViewMode)=>void;fullscreen:boolean;onFullscreen:()=>void}){
 return <div className="simulator-toolbar">
  <div className="viewport-label"><span className="viewport-id">{trackId.toUpperCase()}</span>{!calibration&&<div className="camera-mode-switch" role="group" aria-label="Vista de la pista"><button type="button" aria-pressed={viewMode==='top'} onClick={()=>onViewMode('top')}><Map size={14}/><span>Superior</span></button><button type="button" aria-pressed={viewMode==='perspective'} onClick={()=>onViewMode('perspective')}><Box size={14}/><span>Perspectiva</span></button><button type="button" aria-pressed={viewMode==='follow'} onClick={()=>onViewMode('follow')}><LocateFixed size={14}/><span>Seguir IROH</span></button></div>}</div>
  <div className="viewport-tools">{!calibration&&<><div className="zoom-tools"><IconButton icon={Minus} label="Alejar pista" disabled={zoom<=.75} onClick={()=>onZoom(Math.max(.75,zoom-.25))}/><output aria-label="Zoom de pista">{Math.round(zoom*100)}%</output><IconButton icon={Plus} label="Acercar pista" disabled={zoom>=2} onClick={()=>onZoom(Math.min(2,zoom+.25))}/><IconButton icon={fullscreen?Minimize2:Maximize2} label={fullscreen?'Salir de pantalla completa':'Pantalla completa del simulador'} onClick={onFullscreen}/></div><span className="toolbar-separator"/></>}<button className={calibration?'calibration-toggle active':'calibration-toggle'} aria-pressed={calibration} onClick={onCalibration} title={calibration?'Salir del modo calibración':'Calibrar sensores'}>{calibration?<X size={16}/>:<SlidersHorizontal size={16}/>}<span>{calibration?'Salir de calibración':'Calibrar'}</span></button></div>
 </div>;
}
