import {Link} from 'react-router-dom';
import {ArrowRight,ArrowUpRight,BookOpen,Code2,MapPin,ScanLine,ShieldCheck,Terminal} from 'lucide-react';
import {useAuth} from '../auth/AuthProvider';
import {initialSites} from '../../content/sites';

export function ResourcesPage({onGuide}:{onGuide:()=>void}){
  return <main id="main" className="content-page"><header className="page-heading"><span className="eyebrow">02 / Cuaderno de laboratorio</span><h1>Entiende la señal.<br/>Decide qué hacer.</h1><p>Conceptos y herramientas para pasar de una idea a un programa que puedas probar.</p></header><div className="resource-layout"><section className="resource-main"><article className="resource-row"><span className="resource-index">01</span><div><span className="eyebrow">Antes de ejecutar</span><h2>Divide el desafío en decisiones.</h2><p>¿Qué debe leer el IROH? ¿Qué condición cambia su movimiento? Escribe una tarea pequeña, pruébala y observa el resultado antes de añadir la siguiente.</p><Link className="text-link" to="/intermedio/s01">Abrir el laboratorio<ArrowRight size={16}/></Link></div><Code2 size={25}/></article><article className="resource-row"><span className="resource-index">02</span><div><span className="eyebrow">Mide antes de comparar</span><h2>Un umbral empieza con una lectura.</h2><p>En S01, abre Calibrar. Mueve el robot por blanco y línea, compara los mínimos y máximos de cada sensor y elige un umbral. La referencia guardada no modifica tu programa automáticamente.</p><span className="resource-note">Teclado: flechas para mover · Mayús + flechas para pasos mayores</span></div><ScanLine size={25}/></article><article className="resource-row"><span className="resource-index">03</span><div><span className="eyebrow">API del robot</span><h2>Consulta una función cuando la necesites.</h2><p>Movimiento, sensores, sonar y pantalla. La guía reúne firmas, parámetros y ejemplos breves de las librerías IROH utilizadas en el taller.</p><button className="text-link" onClick={onGuide}>Explorar funciones<ArrowRight size={16}/></button></div><BookOpen size={25}/></article></section><aside className="code-reference"><div><Terminal size={17}/><span>Tu punto de partida</span><code>.ino</code></div><pre><span className="code-comment">{'// Prepara el robot una vez.\n'}</span>{'void setup() {\n  inicializarMovimiento();\n  inicializarSensores();\n  inicializarPantalla();\n}\n\n'}<span className="code-comment">{'// Observa. Decide. Actúa.\n'}</span>{'void loop() {\n  // Tu estrategia empieza aquí.\n}'}</pre><p>El simulador interpreta un subconjunto de Arduino/C++ y la API IROH. No reemplaza todas las librerías de Arduino ni las pruebas en un robot físico.</p><Link className="button" to="/">Volver al inicio<ArrowRight size={16}/></Link></aside></div></main>;
}

export function SitesPage(){
  const {sites,membership}=useAuth();const catalog=sites.length?sites:initialSites;
  return <main id="main" className="content-page"><header className="page-heading"><span className="eyebrow">03 / Comunidad de aprendizaje</span><h1>Un laboratorio.<br/>Distintos lugares para aprender.</h1><p>BITIRO Lab conecta la práctica personal con tu comunidad. El catálogo inicial reúne las sedes del programa de Robótica Educativa de Fundación Mustakis.</p></header><div className="directory-heading"><span>Fundación Mustakis</span><span>{catalog.length} sedes · Chile</span></div><div className="site-directory">{catalog.map((site,index)=><article className="site-row" key={site.id}><span className="site-number">{String(index+1).padStart(2,'0')}</span><MapPin size={21}/><div><h2>{site.name}{membership?.site_id===site.id&&<span className="tag success">Tu sede</span>}</h2><p>{site.partner}</p></div><span className="site-region">{site.region}</span></article>)}</div><div className="directory-foot"><p>Crear una cuenta de práctica no equivale a postular ni obtener un cupo en los talleres.</p><a className="text-link" href="https://robotica.fundacionmustakis.org/" target="_blank" rel="noreferrer">Conocer el programa oficial<ArrowUpRight size={16}/></a></div></main>;
}

export function PrivacyPage(){
  return <main id="main" className="content-page reading-page"><header className="page-heading"><span className="eyebrow">Tu información</span><h1>Aprender con claridad.<br/>También sobre tus datos.</h1><p>Así se utiliza la información en esta versión de BITIRO Lab.</p></header><div className="reading-sections"><section><ShieldCheck size={22}/><div><h2>Una cuenta con lo necesario</h2><p>El registro solicita un nombre para mostrar, correo y contraseña. No solicita RUT, dirección, fecha de nacimiento ni documentos de identidad. Puedes usar un nombre de pila o un alias apropiado para tu taller.</p><p>El servicio de autenticación gestiona la contraseña. Los mentores y administradores no pueden verla.</p></div></section><section><MapPin size={22}/><div><h2>Los programas se habilitan después</h2><p>Tu cuenta BITIRO no queda asociada automáticamente a una institución. Un código de acceso puede vincularte a una organización, sede y grupo específicos. Los códigos entregados a participantes no conceden mentoría. Los permisos de mentor se asignan de forma expresa y controlada por la institución.</p></div></section><section><Code2 size={22}/><div><h2>Tu código y tu navegador</h2><p>La práctica libre local puede funcionar sin una cuenta cuando la instalación lo permite. Los espacios institucionales requieren una cuenta. El código, las sesiones exploradas y las referencias de calibración se guardan en este navegador y se separan por cuenta y grupo institucional. Descarga tu archivo .ino si usarás otro equipo o vas a borrar los datos del navegador.</p><p>La simulación se ejecuta en tu dispositivo. Esta versión no envía el contenido de tus programas a servicios de analítica ni verifica logros académicos automáticamente.</p></div></section><section><BookOpen size={22}/><div><h2>Tu participación en el programa</h2><p>El acceso a BITIRO Lab es independiente de la admisión a talleres. Las autorizaciones y condiciones del programa educativo se gestionan a través de sus canales oficiales. Los contenidos institucionales se habilitan según el grupo y las decisiones del mentor.</p></div></section></div><Link className="text-link" to="/espacios">Volver a mis espacios<ArrowRight size={16}/></Link></main>;
}
