import {useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {ArrowLeft,LogOut,LoaderCircle,ShieldCheck} from 'lucide-react';
import {useAuth} from '../auth/AuthProvider';

const roles={participant:'Participante',facilitator:'Facilitador',admin:'Administrador de plataforma'};
export function AccountPage(){
  const auth=useAuth(),navigate=useNavigate(),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const site=auth.sites.find(item=>item.id===auth.membership?.site_id);
  async function signOut(){setBusy(true);setError('');try{await auth.signOut();navigate('/',{replace:true});}catch{setError('No pudimos cerrar la sesión. Inténtalo nuevamente.');}finally{setBusy(false);}}
  return <main id="main" className="content-page"><Link className="text-link" to="/espacios"><ArrowLeft size={16}/>Volver a mis espacios</Link><div className="page-heading"><span className="eyebrow">Cuenta BITIRO</span><h1>Tu cuenta BITIRO.</h1><p>Tu cuenta es independiente de cada institución. Los espacios y grupos se habilitan mediante códigos.</p></div>
    {auth.status==='loading'?<p className="form-message" role="status">Cargando tu cuenta…</p>:auth.status!=='authenticated'?<section className="profile-panel"><h2>{auth.status==='unconfigured'?'Las cuentas aún no están habilitadas.':'Ingresa para ver tu cuenta.'}</h2><p>Ingresa para consultar tus datos y espacios institucionales.</p><div className="button-row">{auth.status!=='unconfigured'&&<Link className="primary" to="/login?next=/cuenta">Ingresar</Link>}<Link className="button" to="/">Volver al inicio</Link></div></section>:<div className="profile-grid"><section className="profile-panel" aria-labelledby="profile-title"><h2 id="profile-title">Datos de tu cuenta</h2>{auth.error&&<div className="form-error" role="alert"><p>No pudimos cargar toda la información de tu perfil.</p><button type="button" className="button" onClick={()=>{setError('');void auth.refreshProfile().catch(()=>setError('No pudimos actualizar el perfil. Inténtalo nuevamente.'));}}>Reintentar</button></div>}<dl className="definition-list"><div><dt>Nombre visible</dt><dd>{auth.profile?.display_name||'Pendiente de cargar'}</dd></div><div><dt>Correo</dt><dd>{auth.user?.email||'No disponible'}</dd></div><div><dt>Rol efectivo</dt><dd>{auth.membership?roles[auth.membership.role]:'Sin asignación disponible'}</dd></div><div><dt>Sede de plataforma</dt><dd>{site?.name||'No aplica'}</dd></div>{site&&<div><dt>Ubicación</dt><dd>{site.city}, {site.region}</dd></div>}</dl><p className="form-caption">Las sedes y grupos de programas institucionales se muestran dentro de Mis espacios.</p></section><section className="profile-panel" aria-labelledby="account-access"><ShieldCheck size={23}/><h2 id="account-access">Acceso y privacidad</h2><p>Los permisos de facilitador y administrador son asignados por la plataforma. No cambian al editar datos locales.</p><p>La cuenta no implica que tu código esté sincronizado. Revisa el estado de guardado del editor y descarga una copia de tu trabajo.</p><div className="button-row"><Link className="button" to="/actualizar-clave">Cambiar contraseña</Link><Link className="text-link" to="/privacidad">Privacidad y datos</Link></div>{error&&<p className="form-error" role="alert">{error}</p>}<button type="button" className="button" onClick={()=>void signOut()} disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<LogOut size={17}/>} {busy?'Cerrando sesión…':'Cerrar sesión'}</button></section></div>}
  </main>;
}
