import {useEffect,useState,useRef,useCallback} from 'react';
import {Search,UsersRound,RefreshCw,X,Check,MapPin} from 'lucide-react';
import {useAuth} from '../auth/AuthProvider';
import type {Role} from '../auth/auth-types';
import {listMembersPage,updateMember,type AdminMember} from './admin-service';
const roleNames:Record<Role,string>={participant:'Participante',facilitator:'Facilitador',admin:'Administrador'};
export function AdminPage(){
  const {membership,sites,user,refreshProfile}=useAuth();const isAdmin=membership?.role==='admin';
  const [members,setMembers]=useState<AdminMember[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[siteFilter,setSiteFilter]=useState('');
  const [editing,setEditing]=useState<AdminMember|null>(null),[role,setRole]=useState<Role>('participant'),[siteId,setSiteId]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
  const [offset,setOffset]=useState(0),[total,setTotal]=useState(0),[search,setSearch]=useState('');
  const request=useRef(0),editorHeading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{const timer=setTimeout(()=>{setSearch(query);setOffset(0);},250);return()=>clearTimeout(timer);},[query]);
  const load=useCallback(async()=>{const version=++request.current;setLoading(true);setError('');try{const page=await listMembersPage({limit:25,offset,query:search,siteId:siteFilter});if(version===request.current){setMembers(page.members);setTotal(page.total);}}catch(e){if(version===request.current)setError(e instanceof Error?e.message:'No pudimos cargar los participantes.');}finally{if(version===request.current)setLoading(false);}},[offset,search,siteFilter]);
  useEffect(()=>{void load();return()=>{request.current++;};},[load]);
  useEffect(()=>{if(editing)editorHeading.current?.focus();},[editing]);
  const visible=members;
  async function save(){if(!editing)return;setSaving(true);setError('');try{await updateMember({userId:editing.profile.id,siteId,role});setMessage('Sede y permisos actualizados.');const own=editing.profile.id===user?.id;setEditing(null);await load();if(own)await refreshProfile();}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar el cambio.');}finally{setSaving(false);}}
  return <main id="main" className="content-page"><header className="page-heading"><span className="eyebrow">Acompañar el aprendizaje</span><h1>{isAdmin?'Personas y sedes.':'Tu comunidad de práctica.'}</h1><p>{isAdmin?'Organiza las cuentas y asigna responsabilidades en cada sede.':'Consulta los participantes de tu sede y acompaña su recorrido.'}</p></header><div className="admin-context"><UsersRound size={20}/><span>{isAdmin?'Administración de plataforma':'Vista de facilitador'}</span><span className="tag">{loading?'Cargando…':`${total} perfiles`}</span></div><div className="directory-tools"><label className="search-field"><Search size={18}/><input type="search" aria-label="Buscar participante" placeholder="Buscar por nombre" value={query} onChange={e=>setQuery(e.target.value)}/></label>{isAdmin&&<label><span className="sr-only">Filtrar por sede</span><select value={siteFilter} onChange={e=>{setSiteFilter(e.target.value);setOffset(0);}}><option value="">Todas las sedes</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<button className="icon-button" onClick={()=>void load()} aria-label="Actualizar participantes" disabled={loading}><RefreshCw size={18}/></button></div>{message&&<p className="form-message" role="status">{message}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
    {loading?<p className="empty-state" role="status">Cargando participantes…</p>:!visible.length?<div className="empty-state"><UsersRound size={30}/><h2>{query||siteFilter?'No encontramos coincidencias.':'Aún no hay participantes para mostrar.'}</h2><p>{query||siteFilter?'Prueba con otro nombre o selecciona otra sede.':'Las cuentas aparecerán aquí cuando se registren y confirmen su acceso.'}</p></div>:<div className="member-table-wrap"><table className="member-table"><caption className="sr-only">Participantes accesibles según tus permisos</caption><thead><tr><th>Participante</th><th>Sede</th><th>Rol</th>{isAdmin&&<th><span className="sr-only">Acciones</span></th>}</tr></thead><tbody>{visible.map(m=><tr key={m.profile.id}><td><strong>{m.profile.display_name}</strong>{m.profile.id===user?.id&&<span className="inline-note">Tu cuenta</span>}</td><td><span className="site-cell"><MapPin size={14}/>{m.site?.name??'Sin sede'}</span></td><td><span className="tag">{roleNames[m.membership.role]}</span></td>{isAdmin&&<td><button onClick={()=>{setEditing(m);setRole(m.membership.role);setSiteId(m.membership.site_id??'');setError('');setMessage('');}} aria-label={`Editar permisos de ${m.profile.display_name}`}>Editar</button></td>}</tr>)}</tbody></table></div>}
    {total>25&&<nav className="pagination" aria-label="Páginas de participantes"><button disabled={loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>Anterior</button><span role="status">{offset+1}–{Math.min(offset+25,total)} de {total}</span><button disabled={loading||offset+25>=total} onClick={()=>setOffset(offset+25)}>Siguiente</button></nav>}
    {editing&&<section className="member-editor" aria-labelledby="member-edit-title"><div className="section-heading"><div><span className="eyebrow">Cambio de permisos</span><h2 id="member-edit-title" ref={editorHeading} tabIndex={-1}>{editing.profile.display_name}</h2></div><button className="icon-button" aria-label="Cancelar cambio de permisos" onClick={()=>setEditing(null)} disabled={saving}><X size={19}/></button></div><p>Revisa la sede y el rol antes de guardar. Un administrador puede gestionar todas las sedes.</p><div className="form-grid"><label className="form-field">Sede<select value={siteId} onChange={e=>setSiteId(e.target.value)}>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="form-field">Rol<select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="participant">Participante</option><option value="facilitator">Facilitador</option><option value="admin">Administrador de plataforma</option></select></label></div><div className="button-row"><button className="primary" onClick={()=>void save()} disabled={saving}><Check size={16}/>{saving?'Guardando…':'Guardar cambios'}</button><button onClick={()=>setEditing(null)} disabled={saving}>Cancelar</button></div></section>}
  </main>;
}
