import {it,expect} from 'vitest';
import {create,program} from './helpers';
import {irohSpeedToCmS} from '../../simulator/runtime/Movement';
import lcd from '../reference-programs/lcd.cpp?raw';
import pause from '../reference-programs/pause.cpp?raw';
it('keeps 0 as a true stop while preserving the calibrated positive PWM range',()=>{expect(irohSpeedToCmS(0)).toBe(0);expect(irohSpeedToCmS(50)).toBeCloseTo(28*100/150);expect(irohSpeedToCmS(100)).toBe(28);expect(irohSpeedToCmS(200)).toBe(28);});
it('motor mode changes and detenerse wait exactly 70 simulated ms',()=>{const {engine,runtime}=create(program('avanzar(20);pausa(100);retroceder(20);pausa(100);detenerse();'));runtime.step(70);expect(engine.robot.leftMotor).toBe(0);runtime.step(10);expect(engine.robot.leftMotor).toBeGreaterThan(0);runtime.step(100);expect(engine.robot.leftMotor).toBe(0);runtime.step(60);expect(engine.robot.leftMotor).toBe(0);runtime.step(10);expect(engine.robot.leftMotor).toBeLessThan(0);runtime.step(100);expect(engine.robot.leftMotor).toBe(0);});
it.each([['girarDerecha(20);',1,-1],['girarIzquierda(20);',-1,1],['retroceder(10,40);',-1,-1],['avanzar(10,40);',1,1]])('connects %s',(code,left,right)=>{const {engine,runtime}=create(program(code));runtime.step(80);expect(Math.sign(engine.robot.leftMotor)).toBe(left);expect(Math.sign(engine.robot.rightMotor)).toBe(right);});
it('pausa keeps motors moving and later detenerse stops them',()=>{const {engine,runtime}=create(pause);runtime.step(100);const y=engine.robot.y;runtime.step(500);expect(engine.robot.y).toBeLessThan(y);runtime.step(500);expect(engine.robot.leftMotor).toBe(0);const stopped=engine.robot.y;runtime.step(400);expect(engine.robot.y).toBe(stopped);});
it('LCD initialization, numeric overload and overwrite without clearing',()=>{const {engine,runtime}=create(lcd);runtime.step(10);expect(engine.robot.lcd).toEqual(['HOLAghtRobotics ', '123             ']);});
it('LCD clear, clipping, const char and backlight',()=>{const {engine,runtime}=create(program('const char text[]="ABCDE";inicializarPantallaRobot();borrarPantalla();escribirPantalla(14,0,text);apagarPantalla();pausa(100);prenderPantalla();'));runtime.step(10);expect(engine.robot.lcd[0]).toBe('              AB');expect(engine.robot.lcdBacklight).toBe(false);runtime.step(100);expect(engine.robot.lcdBacklight).toBe(true);});
it('button wait yields until stimulus and millis reads simulation time',()=>{const {engine,runtime}=create(program('inicializarPantalla();borrarPantalla();botonInicio();escribirPantalla(0,0,leerBoton());escribirPantalla(0,1,millis());'));runtime.step(300);expect(engine.robot.lcd[0].trim()).toBe('');runtime.command({type:'button',value:true});runtime.step(10);expect(engine.robot.lcd.map(s=>s.trim())).toEqual(['1','300']);});
it('line, IR and sonar read the current scene',()=>{const {engine,runtime}=create(program('inicializarPantalla();borrarPantalla();escribirPantalla(0,0,leerSensorLineaCentral());escribirPantalla(0,1,leerDistanciaSonar());if(leerSensorObstaculoIzquierdo() && !leerSensorObstaculoDerecho())moverServoGolpe(1);'),false);engine.command({type:'ir',side:'left',value:true});const sensor=engine.robot.lineCenter,sonar=engine.robot.sonarCm;runtime.step(10);expect(engine.robot.lcd.map(s=>s.trim())).toEqual([String(sensor),String(sonar)]);expect(engine.robot.strikeServoPosition).toBe(1);});
it('IR obstacle readers stay inactive until the student stimulus is enabled',()=>{const {engine,runtime}=create(program('inicializarGolpe();if(leerSensorObstaculoIzquierdo() || leerSensorObstaculoDerecho())moverServoGolpe(1);'));runtime.step(10);expect(engine.robot.strikeServoPosition).toBe(0);});
it('finPrograma finishes safely after brake, clearing and switching off LCD',()=>{const {engine,runtime}=create(program('inicializarPantalla();escribirPantalla(0,0,"FIN");pausa(500);finPrograma();'));runtime.step(570);expect(engine.status).toBe('running');runtime.step(10);expect(engine.status).toBe('finished');expect(engine.robot.lcd).toEqual(['                ','                ']);expect(engine.robot.lcdBacklight).toBe(false);expect(runtime.diagnostic).toBeNull();runtime.step(1000);expect(engine.robot.simTimeMs).toBe(570);});
it('servo movement is animated and impulse is progressive, snapshots immutable',()=>{const {engine,runtime}=create(program('inicializarGolpe();moverServoGolpe(-1);pausa(1000);'),false,117);const initial=engine.snapshot();runtime.step(10);expect(engine.robot.strikeServoAngle).toBe(93);expect(engine.obstacles[0].x).toBeLessThan(initial.obstacles[0].x);expect(engine.obstacles[0].x).toBeGreaterThan(initial.obstacles[0].x-1);runtime.step(300);expect(engine.robot.strikeServoAngle).toBe(165);expect(initial.obstacles[0].x).toBe(46);});

it('initialization attaches servo and leaves the library logical center at zero',()=>{const {engine,runtime}=create(program('moverServoGolpe(1);pausa(100);inicializarGolpeRobot();pausa(100);moverServoGolpe(-1);'));runtime.step(100);expect(engine.robot.strikeServoAttached).toBe(false);expect(engine.robot.strikeServoAngle).toBe(90);runtime.step(10);expect(engine.robot.strikeServoAttached).toBe(true);expect(engine.robot.strikeServoPosition).toBe(0);runtime.step(400);expect(engine.robot.strikeServoAngle).toBe(165);});
it('initial LCD has exactly sixteen columns',()=>{const {engine,runtime}=create(program('inicializarPantalla();'));runtime.step(10);expect(engine.robot.lcd[0]).toBe(' KnightRobotics ');expect(engine.robot.lcd.every(row=>row.length===16)).toBe(true);});
